package dev.jazalewski1.matchpoint.feature.match.main.detail

internal const val INDICATION_PULSE_HALF_DURATION_MS = 400
internal const val INDICATION_PULSE_FULL_DURATION_MS = INDICATION_PULSE_HALF_DURATION_MS * 2
internal const val INDICATION_PULSE_REPS = 5
internal const val INDICATION_TOTAL_DURATION_MS =
    INDICATION_PULSE_REPS * INDICATION_PULSE_FULL_DURATION_MS
internal const val POINT_INDICATION_PULSE_REPS = 3
internal const val POINT_INDICATION_TOTAL_DURATION_MS =
    POINT_INDICATION_PULSE_REPS * INDICATION_PULSE_FULL_DURATION_MS
