package dev.jazalewski1.matchpoint.core.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF2814E2)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC9C5F1)
val onPrimaryContainerLight = Color(0xFF0B063B)
val secondaryLight = Color(0xFF6414E3)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCAB1F1)
val onSecondaryContainerLight = Color(0xFF201632)
val tertiaryLight = Color(0xFFE35113)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE35113)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFF940F0F)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFC28383)
val onErrorContainerLight = Color(0xFF691515)
val backgroundLight = Color(0xFFFBF8FF)
val onBackgroundLight = Color(0xFF1A1B21)
val surfaceLight = Color(0xFFFBF8FF)
val onSurfaceLight = Color(0xFF1A1B21)
val surfaceVariantLight = Color(0xFFE2E1EC)
val onSurfaceVariantLight = Color(0xFF45464F)
val outlineLight = Color(0xFF767680)
val outlineVariantLight = Color(0xFFC6C5D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF2F0F7)
val inversePrimaryLight = Color(0xFFB8C4FF)
val surfaceDimLight = Color(0xFFDBD9E0)
val surfaceBrightLight = Color(0xFFFBF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F2FA)
val surfaceContainerLight = Color(0xFFEFEDF4)
val surfaceContainerHighLight = Color(0xFFE9E7EF)
val surfaceContainerHighestLight = Color(0xFFE3E1E9)
