name: Android Validation
run-name: ${{ github.event.pull_request.title }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    paths:
      - 'android/**'

jobs:
  formatting:
    name: Validate formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true

      - name: Validate
        working-directory: "android"
        run: ./gradlew spotlessCheck

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true

      - name: Run
        working-directory: "android"
        run: ./gradlew test
