name: Common Validation
run-name: ${{ github.event.pull_request.title }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  pr-title-validation:
    name: Validate PR title

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate
        run: >
          .github/scripts/validate-pr-title "${{ github.event.pull_request.title }}"
